services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
      
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      PGUSER: postgres
      POSTGRES_DB: pokeapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: md5